trigger:
- main  # or your branch name

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseNode@1
  inputs:
    versionSpec: '14.x'  # Specify the Node.js version you need
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'Install Dependencies'

- script: |
    npm test
  displayName: 'Run Tests'

- script: |
    npm run build
  displayName: 'Build Application'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(System.DefaultWorkingDirectory)/build'  # Adjust path if needed
    artifactName: 'build'
  displayName: 'Publish Build Artifact'