trigger: 
- main

stages:
- stage: build
  jobs:
  - job: build
    pool:
      name: Default
    steps:
    - task: Npm@1
      inputs:
        command: 'install'
    - task: Npm@1
      inputs:
        command: 'custom'
        customCommand: 'run build'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: 'build'
        ArtifactName: 'drop'
        publishLocation: 'Container'
    


- stage: deploy
  jobs:
  - job: deploy
    pool:
      name: Default
    steps:
    - task: DownloadBuildArtifacts@1
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'drop'
        downloadPath: '$(System.ArtifactsDirectory)'
    - task: AzureRmWebAppDeployment@4
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'Azure subscription 1(eeb95bf7-53c2-4046-9a59-f4321aba446f)'
        appType: 'webAppLinux'
        WebAppName: 'Doctordoom'
        packageForLinux: '$(System..ArtifactsDirectory)build'
        RuntimeStack: 'STATICSITE|1.0'